#!/usr/bin/env nextflow
/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CRCHUM-CITADEL/nextflow-cbioportal
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Github : https://github.com/CRCHUM-CITADEL/nextflow-cbioportal
----------------------------------------------------------------------------------------
*/

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPORT FUNCTIONS / MODULES / SUBWORKFLOWS / WORKFLOWS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

include { GENOMIC   } from './workflows/genomic.nf'
include { CLINICAL  } from './workflows/clinical.nf'
include { PIPELINE_INITIALISATION } from './subworkflows/local/utils'
include { PIPELINE_COMPLETION     } from './subworkflows/local/utils'
include { PACKAGE_CBIOPORTAL      } from './modules/local/package_cbioportal'

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    RUN MAIN WORKFLOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

workflow {

    main:

    //
    // SUBWORKFLOW: Run initialisation tasks and checks
    //
    PIPELINE_INITIALISATION (
        params.version,
        params.monochrome_logs,
        args,
        params.mode,
        params.outdir,
        params.genomic_samplesheet,
        params.clinical_samplesheet,
        params.study_id,
        params.project_description,
    )

    //
    // WORKFLOW: Run main workflow
    //
    if (params.mode in ['genomic', 'both']){

        ch_vep_data    = params.vep_data    ? Channel.fromPath(params.vep_data)    : Channel.empty()
        ch_pcgr_data   = params.pcgr_data   ? Channel.fromPath(params.pcgr_data)   : Channel.empty()
        ch_mafsmith_data = params.mafsmith_data ? Channel.fromPath(params.mafsmith_data) : Channel.empty()

        // cosmic_data / chimer_data are passed on as plain param strings, not channels —
        // GENOMIC_ML tests them with a truth check to decide whether to run the ML SV
        // step, which a channel cannot answer. (Two ch_* channels built here were never
        // wired to anything and have been removed.)

        ch_hotspots_data = params.cancer_hotspots_data ? Channel.fromPath(params.cancer_hotspots_data).first() : Channel.value([])

        needs_vep_download      = !params.vep_data
        needs_pcgr_download     = !params.pcgr_data
        needs_mafsmith_download = !params.mafsmith_data

        GENOMIC (
            PIPELINE_INITIALISATION.out.genomic_samplesheet,
            params.ensembl_annotations,
            ch_vep_data,
            ch_pcgr_data,
            ch_mafsmith_data,
            needs_vep_download,
            needs_pcgr_download,
            needs_mafsmith_download,
            params.genome_reference,
            params.cosmic_data,
            params.chimer_data,
            ch_hotspots_data,
        )
    }

    if (params.mode == 'clinical'){
        CLINICAL(
            PIPELINE_INITIALISATION.out.clinical_samplesheet,
            params.sample_registrations,
            Channel.value(""),   // no genomic filter in clinical-only mode
        )
    }

    if (params.mode == 'both'){
        // In "both" mode, the linking file is generated by GENOMIC — wait for it
        ch_linking_file = GENOMIC.out.linking_file
            .map { group, f -> f }
            .first()

        // Pass the linking file path as a string so BUILD_CLINICAL_TABLE can filter to genomic subjects
        ch_genomic_subjects = GENOMIC.out.linking_file
            .map { group, f -> f.toString() }
            .first()

        CLINICAL(
            PIPELINE_INITIALISATION.out.clinical_samplesheet,
            ch_linking_file,
            ch_genomic_subjects,
        )
    }

    //
    // MODULE: Package the study files into <study>.tar.gz
    //
    // Packaging lives here rather than inside GENOMIC so that in "both" mode the
    // archive matches the study directory: genomic + clinical + timeline + linking file.
    // Only genomic/both produce a per-group study directory — in clinical-only mode the
    // files are published flat into outdir, so there is nothing to package.
    //
    if (params.mode in ['genomic', 'both']) {
        ch_package_files = GENOMIC.out.package_files

        if (params.mode == 'both') {
            ch_package_files = ch_package_files.mix(CLINICAL.out.package_files)
        }

        PACKAGE_CBIOPORTAL(ch_package_files.groupTuple())
    }

    //
    // SUBWORKFLOW: Run completion tasks
    //
    PIPELINE_COMPLETION (
        params.email,
        params.email_on_fail,
        params.plaintext_email,
        params.outdir,
        params.monochrome_logs,
        params.hook_url,
    )
}

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    THE END
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
