#!/usr/bin/env nextflow
/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CRCHUM-CITADEL/nextflow-sante-precision
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Github : https://github.com/CRCHUM-CITADEL/nextflow-sante-precision
----------------------------------------------------------------------------------------
*/

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPORT FUNCTIONS / MODULES / SUBWORKFLOWS / WORKFLOWS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

include { GENOMIC   } from './workflows/genomic.nf'
include { CLINICAL  } from './workflows/clinical.nf'
include { PIPELINE_INITIALISATION } from './subworkflows/local/utils'
include { PIPELINE_COMPLETION     } from './subworkflows/local/utils'

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    RUN MAIN WORKFLOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

workflow {

    main:

    //
    // SUBWORKFLOW: Run initialisation tasks and checks
    //
    PIPELINE_INITIALISATION (
        params.version,
        params.monochrome_logs,
        args,
        params.mode,
        params.outdir,
        params.genomic_samplesheet,
        params.clinical_samplesheet,
        params.study_id,
        params.project_description,
    )

    //
    // WORKFLOW: Run main workflow
    //
    if (params.mode in ['genomic', 'both']){

        ch_vep_data    = params.vep_data    ? Channel.fromPath(params.vep_data)    : Channel.empty()
        ch_pcgr_data   = params.pcgr_data   ? Channel.fromPath(params.pcgr_data)   : Channel.empty()
        ch_cosmic_data = params.cosmic_data ? Channel.fromPath(params.cosmic_data) : Channel.empty()

        ch_chimer_data = params.chimer_data ? Channel.fromPath(params.chimer_data) : Channel.empty()

        needs_vep_download  = !params.vep_data
        needs_pcgr_download = !params.pcgr_data

        GENOMIC (
            PIPELINE_INITIALISATION.out.genomic_samplesheet,
            params.ensembl_annotations,
            params.ensembl_annotations_expr,
            ch_vep_data,
            ch_pcgr_data,
            needs_vep_download,
            needs_pcgr_download,
            params.genome_reference,
            params.cosmic_data,
            params.chimer_data,
        )
    }

    if (params.mode == 'clinical'){
        CLINICAL(
            PIPELINE_INITIALISATION.out.clinical_samplesheet,
            params.sample_registrations,
        )
    }

    if (params.mode == 'both'){
        // In "both" mode, the linking file is generated by GENOMIC — wait for it
        ch_linking_file = GENOMIC.out.linking_file
            .map { group, f -> f }
            .first()

        CLINICAL(
            PIPELINE_INITIALISATION.out.clinical_samplesheet,
            ch_linking_file,
        )
    }


    //
    // SUBWORKFLOW: Run completion tasks
    //
    PIPELINE_COMPLETION (
        params.email,
        params.email_on_fail,
        params.plaintext_email,
        params.outdir,
        params.monochrome_logs,
        params.hook_url,
    )
}

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    THE END
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
